### ISSUE TITLE
Generalize the client?

### ISSUE THREAD

**Issue by F21** [shurcooL/githubql#1]
Going by the examples, it looks like this might be great as a general graphql client that should be able to query any graphql server. Maybe a command line tool can be provided to run an introspection query against a graphql server to generate the appropriate types as well.

**Comment by shurcooL** [comment]
Yes, in the long term, absolutely.

As I wrote in https://github.com/google/go-github/issues/646:

> - It's very likely the end result package can be entirely generated. The GraphQL schema is entirely introspectable and very structured, and strongly typed. See https://developer.github.com/v4/guides/intro-to-graphql/#discovering-the-graphql-api. Aside from prototyping an initial version, there's really no need to write/maintain the entire package manually.
>
> - Nothing about this is GitHub specific. It's GraphQL specific. A good solution to this will likely apply to any other GraphQL API.

Once development is closer to completed, and this package is more stable and mature, I think I'll see about factoring out the common GraphQL-specific aspects and the generator into a separate component.

`githubql` itself will be 100% specified to GitHub's GraphQL schema, but you will be able to easily create/generate similar Go client libraries for other GraphQL schemas.

It's likely the only parameters the client generator will need is the URL of a GraphQL endpoint (for introspection) and the name.

**Comment by F21** [comment]
Another request I have (once the package is generalized), is to make the transport pluggable. For example, I am currently using graphql over grpc. So, it would be nice if the package comes with a default HTTP transport, but provides an interface so that we can implement other types of transports.

**Comment by shurcooL** [comment]
[`NewClient`](https://godoc.org/github.com/shurcooL/githubql#NewClient) already takes an `*http.Client` parameter. If you leave it as `nil`, then `http.DefaultClient` is used, otherwise the custom HTTP client. A custom transport can be provided as part of a custom `*http.Client`, see [`http.Client.Transport`](https://godoc.org/net/http#Client.Transport).

Is that what you're asking for, or are you referring to something else?

**Comment by F21** [comment]
In terms of GRPC, we do not use the `http.Client` directly although GRPC is built on top of HTTP/2. It is wrapped by the GRPC client which provides more features on top of `http.Client`. Therefore, I can't pass a `http.Client` to `NewClient` if I want to use GRPC as my transport.

Here's a pretty good example of a generated GRPC client being used: https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_client/main.go

**Comment by shurcooL** [comment]
I see. That `NewGreeterClient` func takes a `*grpc.ClientConn`.

I'm not quite sure how to deal with this, but I want to support it if possible. Mind opening a new issue where we can track and discuss it in more detail?

**Comment by shurcooL** [comment]
This issue has been resolved by https://github.com/shurcooL/graphql/commit/6ac8ee219c8da29544f2659097d7d709d6420afe.
