### ISSUE TITLE
Query Interfaces and unions

### ISSUE THREAD

**Issue by ereyes01** [shurcooL/githubql#21]
Thanks for taking a crack at the client library...

How would you query a specific type when the schema specifies an interface or union as the return type?

For instance, say I try the following query to github:

```
query {
  search(first: 100, type: ISSUE, query: \"user:ereyes01 repo:firebase label:enhancement state:open\") {
    nodes {
      ... on Issue {
        number
      }
    }
  }
}
```

The [`search`](https://developer.github.com/v4/reference/query/#connections) query returns a [`SearchResultItem`](https://developer.github.com/v4/reference/union/searchresultitem/), and in this case, I just want the issues. Is there a way using your library to specify the `.. on Issue` part of the query above?

**Comment by shurcooL** [comment]
Hi, yes, GraphQL inline fragments and unions are supported (see #10 for more information), but not documented in README yet. I plan to do that, and tracking it in https://github.com/shurcooL/graphql/issues/3 issue.

The GraphQL query you posted can be expressed something like this:

```Go
var query struct {
	Search struct {
		Nodes []struct {
			Issue struct {
				Number int
			} `graphql:"... on Issue"`
		}
	} `graphql:"search(first: 100, type: ISSUE, query: $searchQuery)`
}
```

**Comment by ereyes01** [comment]
Awesome, and works great. Thanks!
