### ISSUE TITLE
GitHub Enterprise support.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/githubql#23]
GitHub Enterprise has support for GitHub GraphQL API as of 2.10:

Announcement: https://github.com/blog/2373-introducing-github-enterprise-2-10-build-tools-with-the-new-github-graphql-api-organize-with-topics-and-level-up-your-project-management.
Documentation: https://developer.github.com/enterprise/2.10/v4/.

(Also see [this thread](https://platform.github.community/t/is-graphql-available-for-github-enterprise/1224/6) for history behind GitHub GraphQL API support in GitHub Enterprise.)

We should support GitHub Enterprise.

**Comment by shurcooL** [comment]
The root GraphQL endpoint for GitHub Enterprise is custom:

> the GraphQL API v4 has a single endpoint:
>
> ```
> http(s)://[hostname]/api/graphql
> ```
>
> The endpoint remains constant no matter what operation you perform.

_(Source: https://developer.github.com/enterprise/2.11/v4/guides/forming-calls/#the-graphql-endpoint.)_

So we need to let the user provide it to `githubql` library.

**Comment by yc1838** [comment]
Hey I am curious what should I put under host name?

**Comment by CodyGirl** [comment]
Hello Team, is there any Documentation or video about how to use this feature while creating a GitHub dashboard on grafana (for enterprise GitHub instances)?
