### ISSUE TITLE
Support for "expression:" on "object"?

### ISSUE THREAD

**Issue by cgendreau** [shurcooL/githubql#28]
I have the following query (only the Repository section is included) that I tested against the GitHub GraphQL API to get the content of a file as text:
```
...
nodes {
        name
        object(expression: "master:LICENSE") {
          ... on Blob {
            text
          }
        }
      }
...
```
I was wondering how to translate the `object(expression: "master:LICENSE")` for `githubql` ?
I tried the following (without success):
```
Object struct {
     Blob struct {
       Text githubql.String
     }`graphql:"... on Blob"`
 }`graphql:"expression:\"master:LICENSE\""`   
```
->`Error: Parse error on "master:LICENSE" (STRING)`
Please note that I'm a total newbie to Go and I have very limited experience with GraphQL so do not hesitate to point me to the doc if I missed something :)

**Comment by shurcooL** [comment]
> I tried the following (without success)

The GraphQL query has `object(expression: "master:LICENSE")`. You should include the whole thing in the `graphql` tag:

```
} `graphql:"object(expression: \"master:LICENSE\")"`
```

**Comment by cgendreau** [comment]
Thanks for the help @shurcooL

**Comment by kounelisagis** [comment]
Helped a lot @dmitshur
