### ISSUE TITLE
Do I have to send multiple requests one by one to get all nodes?

### ISSUE THREAD

**Issue by laike9m** [shurcooL/githubql#29]
Say I'm fetching followers, using similar code as the [pagination](https://github.com/shurcooL/githubql#pagination) example. Now, if I have 600 followers, does it mean I have to send 6 requests to get them all? And it seems there's no way to parallelize it, since end cursor is needed to perform the next request?

**Comment by shurcooL** [comment]
> Say I'm fetching followers, using similar code as the [pagination](https://github.com/shurcooL/githubql#pagination) example. Now, if I have 600 followers, does it mean I have to send 6 requests to get them all?

Yes, that's right. If the max page size is 100 followers, then you'll need to make 6 requests to fetch all 600 followers.

> And it seems there's no way to parallelize it, since end cursor is needed to perform the next request?

Correct, you need to fetch the pages sequentially, as far as I know.

**Comment by laike9m** [comment]
Thanks for answering.
